#' civic_voting dataset
#'
#' Synthetic civic voting participation data.
#' @format A tibble with 1000 rows and 10 variables.
#' @source Synthetic data generated by civic.icarm team.
"civic_voting"

#' civic_education dataset
#'
#' Synthetic civic education outcomes data.
#' @format A tibble with 800 rows and 9 variables.
#' @source Synthetic data generated by civic.icarm team.
"civic_education"

#' civic_german_credit dataset
#'
#' Synthetic German credit scoring fairness benchmark.
#' @format A tibble with 1000 rows and 8 variables.
#' @source Synthetic data generated by civic.icarm team.
"civic_german_credit"

