#' civic_voting dataset
#'
#' Synthetic civic voting participation data.
#' @format A tibble with 1000 rows and 10 variables.
#' @source Synthetic data generated by civic.icarm team.
"civic_voting"

#' civic_education dataset
#'
#' Synthetic civic education outcomes data.
#' @format A tibble with 800 rows and 9 variables.
#' @source Synthetic data generated by civic.icarm team.
"civic_education"

#' civic_german_credit dataset
#'
#' Synthetic German credit scoring fairness benchmark.
#' @format A tibble with 1000 rows and 8 variables.
#' @source Synthetic data generated by civic.icarm team.
"civic_german_credit"


#' Synthetic Racism and Civic Participation Survey
#'
#' A synthetic dataset of 150 individuals capturing experiences of
#' racism, policing, migration, and civic participation. Designed
#' for fairness auditing, regression, binary, and multi-class
#' classification demonstrations within the DataCitizen-Pro framework.
#'
#' @format A tibble with 150 rows and 16 variables:
#' \describe{
#'   \item{age}{Integer. Age in years (18-75).}
#'   \item{gender}{Factor. male, female, diverse.}
#'   \item{hair_color}{Factor. blonde, brown, black, other.}
#'   \item{skin_color}{Factor. light, medium, dark.}
#'   \item{relationship_status}{Factor. single, engaged, married.}
#'   \item{racism_impact}{Integer 0-10. Perceived racism impact.}
#'   \item{police_stop}{Factor. 0 times, 1 time, 2 or more.}
#'   \item{migrant_status}{Factor. Yes or No.}
#'   \item{income}{Numeric. Monthly income in EUR.}
#'   \item{education_level}{Factor. Education category.}
#'   \item{employment_status}{Factor. Employment category.}
#'   \item{area_type}{Factor. Urban or Rural.}
#'   \item{religion}{Factor. Religion category.}
#'   \item{language_proficiency}{Factor. Language level.}
#'   \item{number_of_friends}{Integer 0-10.}
#'   \item{political_orientation}{Integer 0-3. Left to right.}
#' }
#' @source Synthetic data generated by the civic.icarm team.
#' @examples
#' data(civic_racism_survey)
#' m <- civic_fit(racism_impact ~ ., civic_racism_survey,
#'                model = "linear")
#' ex <- civic_explain(m)
"civic_racism_survey"

#' Synthetic Racism and Civic Participation Survey
#'
#' A synthetic dataset of 1000 individuals capturing experiences of
#' racism, policing, migration, and civic participation. Designed
#' for fairness auditing, regression, binary, and multi-class
#' classification demonstrations within the DataCitizen-Pro framework.
#'
#' @format A tibble with 150 rows and 16 variables:
#' \describe{
#'   \item{age}{Integer. Age in years (18-75).}
#'   \item{gender}{Factor. male, female, diverse.}
#'   \item{hair_color}{Factor. blonde, brown, black, other.}
#'   \item{skin_color}{Factor. light, brown, dark.}
#'   \item{relationship_status}{Factor. single, engaged, married.}
#'   \item{racism_impact}{Integer 0-10. Perceived racism impact.}
#'   \item{police_stop}{Factor. 0 times, 1 time, 2 or more.}
#'   \item{migrant_status}{Factor. Yes or No.}
#'   \item{income}{Numeric. Monthly income in EUR.}
#'   \item{education_level}{Factor. Education category.}
#'   \item{employment_status}{Factor. Employment category.}
#'   \item{area_type}{Factor. Urban or Rural.}
#'   \item{religion}{Factor. Religion category.}
#'   \item{language_proficiency}{Factor. Language level.}
#'   \item{number_of_friends}{Integer 0-10.}
#'   \item{political_orientation}{Integer 0-3. Left to right.}
#' }
#' @source Synthetic data generated by the civic.icarm team.
#' @examples
#' data(civic_racism_survey)
#' m <- civic_fit(racism_impact ~ ., civic_racism_survey,
#'                model = "linear")
"civic_racism_survey"
